title: Ana Maria Restrepo M.
description: Sitio personal

url: http://fmauricios.github.com/ana
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Inicio
   url: /index.html
 - title: Acerca de mi
   url: /about
 - title: Contacto
   url: /contact

social:
   email: anarestrepomejia@gmail.com

google_analytics: "UA-58263416-1"
